In [ ]:
#updated SRTN
at = []
bt = []
pro = []
info = []

n = int(input("Enter the number of process: "))

for i in range(1, n+1):

  pro.append("P%d" %i)
  a = int(input("P%d arrival time: " %i))
  at.append(a)
  b = int(input("P%d burst time: " %i))
  bt.append(b)
  info.append([bt[i-1], at[i-1], i-1])
print(info)


tracker = []

for i in range(sum(bt)):
  
  l = [j for j in info  if j[1] <= i]
  l.sort(key=lambda x : x[0])
  info[info.index(l[0])][0] -= 1
  for k in info:
    if k[0] == 0:
      print("k is : ", k)
      info.pop(info.index(k))
      tracker.append([k, i+1])

print(tracker)
ct = [0] * (n)

for i in tracker:
  ct[i[0][2]] = i[1]
print(ct)


import pandas as pd
chart = {"Process No" : pro,
         "Arrival Time" : at,
         "Burst Time" : bt,
         "Completion Time" : ct}
df = pd.DataFrame(chart)

df["Turn Around Time"] = df["Completion Time"] - df["Arrival Time"]
df["Waiting Time"] = df["Turn Around Time"] - df["Burst Time"]


print()
print("Average Waiting Time: ", df["Waiting Time"].mean())
print()
print("Average Turn Around Time: ", df["Turn Around Time"].mean())

print()

df

Enter the number of process: 4
P1 arrival time: 0
P1 burst time: 5
P2 arrival time: 1
P2 burst time: 3
P3 arrival time: 2
P3 burst time: 4
P4 arrival time: 4
P4 burst time: 1
[[5, 0, 0], [3, 1, 1], [4, 2, 2], [1, 4, 3]]
k is :  [0, 1, 1]
k is :  [0, 4, 3]
k is :  [0, 0, 0]
k is :  [0, 2, 2]
[[[0, 1, 1], 4], [[0, 4, 3], 5], [[0, 0, 0], 9], [[0, 2, 2], 13]]
[9, 4, 13, 5]

Average Waiting Time:  2.75

Average Turn Around Time:  6.0

,Process No,Arrival Time,Burst Time,Completion Time,Turn Around Time,Waiting Time
0,P1,0,5,9,9,4
1,P2,1,3,4,3,0
2,P3,2,4,13,11,7
3,P4,4,1,5,1,0